

spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/server?useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true&characterEncoding=utf8&useSSL=false&noAccessToProcedureBodies=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

# 测试环境打印SQL脚本
logging:
  level:
    com.server.mapper: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl